FROM microsoft/dotnet:2.1-sdk-nanoserver-1709 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-1709
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "samplebackend.dll"]